FORMAT: 1A
HOST: http://www.google.com

# DA
DA Module API is a *device adapter* service to control modules/translators used by DA.

# Group Modules
Modules/Transaltors related resources of the **DA Module API**

## Module Installation [/modules/install/{module}]
Install a module given a key and the module file.
### Install a Module [POST]

+ Parameters
    + module (required, text, `push2.0-att-1.2`) ... Text `module` is the key to be given to the module. Has example value.

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="translator[file]"; filename="transaltor.js"
        Content-Type: text/javascript
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 200 (text/plain)

    + Body

            "received upload."
            
+ Response 400 (text/plain)

    + Body

            "Can't be installed."

## Uninstall Module [/modules/uninstall/{module}]
Uninstall a single module given its key.

+ Parameters
    + module (required, text, `push2.0-att-1.2`) ... Text `module` is the key to be given to the module. Has example value.

### Uninstall a Module [GET]
+ Response 200 (text/plain)

    + Body

            "module uninstalled successfully."

+ Response 400 (text/plain)

    + Body

            "Can't be uninstalled."


## Enable Module [/modules/enable/{module}/{pushVersion_deviceType}]
Enable a single module given its key and push version concatenated with device type.

+ Parameters
    + module (required, text, `push2.0-att-1.2`) ... Text `module` is the key to be given to the module. Has example value.
    + pushVersion_deviceType (required, text, `push2.0 _ att`) ... Text `pushVersion _ deviceType` of the module to link it with protocol. Has example value.

### Enable a Module [GET]
+ Response 200 (text/plain)

    + Body

            "module with key: 'module' is running."
            
+ Response 400 (text/plain)

    + Body

            "Cannot enable module."

## Disable Module [/modules/disable/{module}]
Disable a single module given its key.

+ Parameters
    + module (required, text, `push2.0-att-1.2`) ... Text `module` is the key to be given to the module. Has example value.

### Disable a Module [GET]
+ Response 200 (text/plain)

    + Body

            "module with key: 'module' is disconnected."
            
+ Response 400 (text/plain)

    + Body

            "module with key: 'module' cannot be stopped."

# Group Configuration
Setting configurations of the **DA Configuration API**
## setting configurations [/conf/set]
set (Change) some configuration given a JSON Object contains the new Configurations.
### Change Configurations [POST]
+ Request

        {
            "rabbit": {
                "server": "localhost"
            },
            "reddis": {
                "port": "1131"
            }
        }
        
+ Response 200

        
+ Response 400

        { "errorCode": "E1" }
