FORMAT: 1A
HOST: http://www.google.com

# DA
DA API is a *device adapter* service to control modules/translators used by DA.

# Group Modules
Modules/Transaltors related resources of the **DA Module API**

## Module Installation [/modules/install/{module}]
### Install a Module [POST]

+ Parameters
    + module (required, text, `1`) ... Text `module` of the Note to perform action with. Has example value.

+ Request (application/json)

        { "file": "translator file" }

+ Response 200 (text/plain)

## Uninstall Module [/modules/uninstall/{module}]
Uninstall a single module given its key.

+ Parameters
    + module (required, text, `1`) ... Text `module` of the Note to perform action with. Has example value.

### Uninstall a Module [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }


## Enable Module [/modules/enable/{module}/{pushVersion_deviceType}]
Enable a single module given its key and push version concatenated with device type.

+ Parameters
    + module (required, text, `1`) ... Text `module` of the Note to perform action with. Has example value.
    + pushVersion_deviceType (required, text, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Enable a Module [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

## Disable Module [/modules/disable/{module}]
Disable a single module given its key.

+ Parameters
    + module (required, text, `1`) ... Text `module` of the Note to perform action with. Has example value.

### Disable a Module [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

